---
kind: pipeline
type: docker
name: ci

metadata:
  namespace: drone

platform:
  os: linux
  arch: arm64

#trigger:
#  branch:
#    - master
#  event:
#    - push

trigger:
  branch:
    - main

workspace:
  path: /drone/src

steps:
  - name: Install dependencies
    image: python:3.11-slim
    commands:
      - python3 -m venv .venv
      - source .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  - name: Lint & Test
    image: python:3.11-slim
    commands:
      - source .venv/bin/activate
      - flake8 --statistics
      - pytest -vs --color=yes tests
