---
kind: pipeline
type: docker
name: ci

metadata:
  namespace: drone

platform:
  os: linux
  arch: arm64

#trigger:
#  branch:
#    - master
#  event:
#    - push

trigger:
  branch:
    - main

steps:
  - name: test-colors
    image: alpine
    commands:
      - 'echo -e "\033[1;31mThis is red text\033[0m"'
  - name: test
    image: python:3.11
    commands:
      - pip install --upgrade pip
      - pip install --no-cache-dir pytest==8.3.4
      - pytest -vs tests
