---
kind: pipeline
type: kubernetes
name: ci

metadata:
  namespace: drone

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: test
    image: python3.11-slim
    commands:
      - pip install --upgrade pip
      - pip install --no-cache-dir pytest==8.3.4
      - pytest -vs tests

