---
kind: pipeline
type: docker
name: ci

metadata:
  namespace: drone

platform:
  os: linux
  arch: arm64

#trigger:
#  branch:
#    - master
#  event:
#    - push

trigger:
  branch:
    - main

steps:
  - name: test
    image: python:3.11-slim
    commands:
      - pip install --upgrade pip
      - pip install --no-cache-dir pytest==8.3.4
      - pytest -vs --color=true tests
