---
kind: pipeline
type: docker
name: ci

metadata:
  namespace: drone

platform:
  os: linux
  arch: arm64

#trigger:
#  branch:
#    - master
#  event:
#    - push

trigger:
  branch:
    - main

workspace:
  path: /drone/src

steps:
  - name: Debug environment variables
    image: alpine:latest
    commands:
      - env
      - echo -n "$DRONE_COMMIT_SHA,latest" > .tags

  - name: Install dependencies
    image: python:3.11-slim
    commands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  - name: Lint & Test
    image: python:3.11-slim
    commands:
      - . .venv/bin/activate
      - flake8 --statistics
      - pytest -vs --color=yes tests

  - name: Build & Push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hakimhc/argocd-gh-webhook-util
